-- 用户上传红人名单导入任务（聊天附件 Excel）；由 Scraper Worker 与搜索任务并行消费
CREATE TABLE IF NOT EXISTS tiktok_influencer_import_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  campaign_id VARCHAR(36) NOT NULL COMMENT 'tiktok_campaign.id',
  session_id VARCHAR(36) NULL COMMENT 'campaign_sessions.id',
  import_batch_id VARCHAR(64) NOT NULL COMMENT '本批导入业务 ID',
  batch_group_id VARCHAR(64) NULL COMMENT '平台子任务公共批次号（全部完成后汇总汇报）',
  platform VARCHAR(24) NOT NULL DEFAULT 'mixed' COMMENT '主平台或 mixed（行内可带平台）',
  contact_mode VARCHAR(24) NOT NULL DEFAULT 'recommended_only' COMMENT 'recommended_only=只联系符合投放地区和画像要求且推荐的红人; contact_all=联系符合投放地区的所有红人; do_not_contact=仅排重/不联系（不分析不联系，写入本 campaign 候选表 do_not_contact 标记）',
  priority INT NOT NULL DEFAULT 150 COMMENT '默认高于关键词搜索任务',
  payload JSON NOT NULL COMMENT 'rows: [{ profileUrl, email?, platform? }], summary stats',
  status ENUM('pending','processing','succeeded','failed','cancelled') NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  worker_id VARCHAR(128) NULL,
  worker_host VARCHAR(128) NULL,
  worker_ip VARCHAR(64) NULL,
  last_progress_at DATETIME NULL,
  total_rows INT NOT NULL DEFAULT 0 COMMENT 'Excel 解析有效行数（去重前）',
  skipped_duplicate_count INT NOT NULL DEFAULT 0 COMMENT '候选表已存在跳过',
  parse_error_count INT NOT NULL DEFAULT 0,
  progress_country_checked_count INT NOT NULL DEFAULT 0,
  progress_country_passed_count INT NOT NULL DEFAULT 0,
  progress_enriched_count INT NOT NULL DEFAULT 0,
  progress_analyzed_count INT NOT NULL DEFAULT 0,
  progress_recommended_count INT NOT NULL DEFAULT 0,
  source_file_name VARCHAR(255) NULL,
  source_file_storage_key VARCHAR(512) NULL COMMENT '相对 data/session-imports 的路径',
  error_message TEXT NULL,
  result_summary TEXT NULL COMMENT 'Worker 完成后摘要（聊天回复用）',
  batch_group_reported_at DATETIME NULL COMMENT '批次汇总已汇报时间（防重复汇报）',
  started_at TIMESTAMP NULL DEFAULT NULL,
  finished_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_campaign_import_batch (campaign_id, import_batch_id),
  INDEX idx_campaign_status (campaign_id, status),
  INDEX idx_campaign_batch_group (campaign_id, batch_group_id),
  INDEX idx_status_priority_created (status, priority, id),
  INDEX idx_session_status (session_id, status),
  INDEX idx_worker_status (worker_id, status),
  INDEX idx_created_at (created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户上传红人名单导入任务';
