-- Scraper 任务表：Execution Controller 入队，Scraper Worker 消费
CREATE TABLE IF NOT EXISTS tiktok_influencer_search_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  campaign_id VARCHAR(36) NOT NULL COMMENT 'tiktok_campaign.id',
  session_id VARCHAR(36) NULL COMMENT '关联 campaign_sessions.id，供工作实况订阅路由',
  run_id VARCHAR(64) NULL COMMENT '执行批次 ID（通常为 campaign + date）',
  keyword VARCHAR(255) NULL COMMENT '本任务主关键词（单任务单关键词）',
  keyword_type ENUM('new','variant','high_performer','fallback') NOT NULL DEFAULT 'new',
  priority INT NOT NULL DEFAULT 100 COMMENT '优先级，数字越大越优先',
  payload JSON NOT NULL COMMENT '任务参数，如 targetBatchSize/userMessage/trigger',
  status ENUM('pending','processing','succeeded','failed','cancelled') NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT '已尝试次数',
  worker_id VARCHAR(128) NULL COMMENT '当前处理该任务的 worker 标识',
  worker_host VARCHAR(128) NULL COMMENT '执行机器标识（可选）',
  error_message TEXT NULL COMMENT '失败原因',
  started_at TIMESTAMP NULL DEFAULT NULL,
  finished_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_campaign_run_keyword (campaign_id, run_id, keyword),
  INDEX idx_campaign_status (campaign_id, status),
  INDEX idx_campaign_run (campaign_id, run_id),
  INDEX idx_status_priority_created (status, priority, created_at),
  INDEX idx_worker_status (worker_id, status),
  INDEX idx_session_status (session_id, status),
  INDEX idx_keyword (campaign_id, keyword, created_at),
  INDEX idx_created_at (created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='红人搜索补货任务队列表';

-- 关键词效果闭环评分表（Controller 反思与下一轮派发依据）
CREATE TABLE IF NOT EXISTS tiktok_keyword_run_result (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  campaign_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NULL,
  run_id VARCHAR(64) NOT NULL,
  task_id BIGINT NULL COMMENT '关联 tiktok_influencer_search_task.id',
  keyword VARCHAR(255) NOT NULL,
  keyword_type ENUM('new','variant','high_performer','fallback') NOT NULL DEFAULT 'new',
  assigned_worker VARCHAR(128) NULL,
  assigned_worker_host VARCHAR(128) NULL,
  search_count INT NOT NULL DEFAULT 0,
  enrich_success_count INT NOT NULL DEFAULT 0,
  analyze_recommended_count INT NOT NULL DEFAULT 0,
  insert_candidate_count INT NOT NULL DEFAULT 0,
  insert_execution_count INT NOT NULL DEFAULT 0 COMMENT 'DEPRECATED: 暂未使用，保留兼容',
  duplicate_count INT NOT NULL DEFAULT 0 COMMENT 'DEPRECATED: 暂未使用，保留兼容',
  fail_count INT NOT NULL DEFAULT 0,
  fail_reason VARCHAR(255) NULL,
  elapsed_ms INT NULL,
  score DECIMAL(10,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_campaign_run_keyword (campaign_id, run_id, keyword),
  INDEX idx_campaign_run_keyword (campaign_id, run_id, keyword),
  INDEX idx_campaign_score (campaign_id, score, created_at),
  INDEX idx_task_id (task_id),
  INDEX idx_created_at (created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='关键词任务执行效果评分';
